# Generated by Django 4.1.5 on 2023-01-27 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="books",
            name="id",
        ),
        migrations.RemoveField(
            model_name="library",
            name="id",
        ),
        migrations.AddField(
            model_name="books",
            name="book_id",
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="library",
            name="transaction_id",
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="books",
            name="stock",
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name="UserFine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fine", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
