# Generated by Django 4.1.5 on 2023-01-30 17:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_books_id_remove_library_id_books_book_id_and_more"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="books",
            managers=[
                ("object", django.db.models.manager.Manager()),
            ],
        ),
    ]
