# Generated by Django 4.1.5 on 2023-01-30 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_books_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="books",
            managers=[],
        ),
    ]
