# Generated by Django 4.0.5 on 2023-01-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_books_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='total_stock',
            field=models.IntegerField(default=0),
        ),
    ]
