# Generated by Django 4.0.5 on 2022-11-20 05:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_student_fullname_alter_student_mobileno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobileno',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.CharField(max_length=30, unique=True, verbose_name='Roll No'),
        ),
    ]
