# Generated by Django 4.0.5 on 2022-11-20 05:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_alter_student_mobileno_alter_student_rollno'),
        ('book', '0009_delete_book_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now=True, help_text='Date the book is issued')),
                ('due_date', models.DateTimeField(default=datetime.datetime(2022, 11, 26, 11, 16, 31, 429656), help_text='Date the book is due to')),
                ('date_returned', models.DateField(blank=True, help_text='Date the book is returned', null=True)),
                ('remarks_on_issue', models.CharField(default='Book in good condition', help_text='Book remarks/condition during issue', max_length=100)),
                ('remarks_on_return', models.CharField(default='Book in good condition', help_text='Book remarks/condition during return', max_length=100)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
        ),
    ]
