# Generated by Django 4.0.5 on 2022-11-20 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_issue',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 11, 34, 41, 934991), help_text='Date the book is due to'),
        ),
    ]
