# Generated by Django 4.0.5 on 2023-01-16 16:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_book_issue_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_issue',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 22, 16, 27, 8, 886266), help_text='Date the book is due to'),
        ),
    ]
