# Generated by Django 4.1.3 on 2022-11-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_books_delete_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
