# Generated by Django 4.1.3 on 2022-11-19 17:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('book', '0004_books_summary_alter_books_id_bookinstance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateTimeField(auto_now=True, help_text='Date the book is issued')),
                ('due_date', models.DateTimeField(default=datetime.datetime(2022, 11, 25, 22, 42, 50, 832003), help_text='Date the book is due to')),
                ('date_returned', models.DateField(blank=True, help_text='Date the book is returned', null=True)),
                ('remarks_on_issue', models.CharField(default='Book in good condition', help_text='Book remarks/condition during issue', max_length=100)),
                ('remarks_on_return', models.CharField(default='Book in good condition', help_text='Book remarks/condition during return', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='is_available',
        ),
        migrations.AddField(
            model_name='books',
            name='cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='books',
            name='is_borrowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='books',
            name='id',
            field=models.AutoField(help_text='Unique ID', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='BookInstance',
        ),
        migrations.AddField(
            model_name='book_issue',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.books'),
        ),
        migrations.AddField(
            model_name='book_issue',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student'),
        ),
    ]
