# Generated by Django 4.0.5 on 2022-11-20 05:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_alter_book_issue_due_date_alter_books_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_issue',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 10, 38, 29, 170694), help_text='Date the book is due to'),
        ),
    ]
