# Generated by Django 4.0.5 on 2022-11-20 05:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_book_issue_due_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(help_text='Unique ID', primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100, verbose_name='Book Name')),
                ('book_id', models.IntegerField(help_text='Unique ID', unique=True, verbose_name='Book ID')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('is_borrowed', models.BooleanField(default=False, help_text='Is the book borrowed?')),
                ('summary', models.TextField(blank=True, help_text='Summary of the book', max_length=1000, null=True)),
                ('cost', models.PositiveIntegerField(default=100, help_text='Cost of the book')),
                ('in_stock', models.PositiveIntegerField(default=1, help_text='Number of books in stock')),
            ],
        ),
        migrations.AlterField(
            model_name='book_issue',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 10, 49, 22, 54237), help_text='Date the book is due to'),
        ),
        migrations.AlterField(
            model_name='book_issue',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book'),
        ),
        migrations.DeleteModel(
            name='Books',
        ),
    ]
