# Generated by Django 4.0.5 on 2022-11-20 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_book_alter_book_issue_due_date_alter_book_issue_book_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book_Issue',
        ),
    ]
