# Generated by Django 4.1.5 on 2023-01-16 18:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_student_mobileno_alter_student_rollno'),
        ('book', '0009_delete_book_issue'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.AutoField(help_text='Unique ID', primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=100, verbose_name='Book Name')),
                ('isbn', models.IntegerField(help_text='Unique ID', unique=True, verbose_name='Book ID')),
                ('author', models.CharField(max_length=100, verbose_name='Author')),
                ('summary', models.TextField(blank=True, help_text='Summary of the book', max_length=1000, null=True)),
                ('cost', models.PositiveIntegerField(default=100, help_text='Cost of the book')),
                ('quantity', models.PositiveIntegerField(default=1, help_text='Number of books in stock')),
            ],
        ),
        migrations.RenameField(
            model_name='book',
            old_name='book_id',
            new_name='isbn',
        ),
        migrations.CreateModel(
            name='ReturnBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issuing_code', models.CharField(max_length=100, verbose_name='Issuing Code')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
        ),
        migrations.CreateModel(
            name='BookIssue',
            fields=[
                ('id', models.AutoField(help_text='Unique ID', primary_key=True, serialize=False)),
                ('issuing_code', models.CharField(max_length=100, verbose_name='Issuing Code')),
                ('issue_date', models.DateField(default=datetime.datetime.now, help_text='Date of issue')),
                ('return_date', models.DateField(default=datetime.datetime(2023, 1, 24, 0, 17, 0, 53757), help_text='Date of return')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student')),
            ],
        ),
    ]
