# Generated by Django 4.1.5 on 2023-01-16 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_addbook_rename_book_id_book_isbn_returnbook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookissue',
            name='return_date',
            field=models.DateField(default=datetime.datetime(2023, 1, 24, 0, 39, 59, 741495), help_text='Date of return'),
        ),
    ]
